"""empty message

Revision ID: 426cd2e41a4
Revises: 30c31ed9ee4
Create Date: 2015-01-04 20:37:30.582199

"""

# revision identifiers, used by Alembic.
revision = '426cd2e41a4'
down_revision = '30c31ed9ee4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('air_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'air_date')
    ### end Alembic commands ###
