"""empty message

Revision ID: 4f86dde47a5
Revises: 10a469091a9
Create Date: 2015-01-04 23:24:43.103957

"""

# revision identifiers, used by Alembic.
revision = '4f86dde47a5'
down_revision = '10a469091a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('oauth_token', sa.String(length=256), nullable=True),
    sa.Column('oauth_secret', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('uq_show_id_season_episode', table_name='episode')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_show_id_season_episode', 'episode', ['show_id', 'season', 'episode'], unique=1)
    op.drop_table('user')
    ### end Alembic commands ###
